### ISSUE TITLE
Sqlite3 has being defined as default engine is the database something else?

### ISSUE THREAD

**Issue by thepenguinthatwants** [thomas-maurice/ansible-role-gitea#52]
Hi!

I've mostly used default settings on my ubuntu 18.04 instance.
Database should be sqlite3 and gitea also see it as that.

Problem comes when I use
` /usr/local/bin/gitea dump -c /etc/gitea/gitea.ini`

and then try to restore then it fails.
Weird part is that true and false don’t exist in SQLite3 and it contains in the dump.

**Comment by msgpeek** [comment]
Not sure if I get the question. 

You alone know which DBMS you defined to be used and whether you installed it or not.  And, how does this affect this role/repo? Please elaborate.

**Comment by thepenguinthatwants** [comment]
Just like I havent made any changes just ran the installation and the settings from https://github.com/thomas-maurice/ansible-role-gitea/blob/master/defaults/main.yml gitea_db_type: sqlite3

I am wondering if instead of using sqlite3 it made another type of database. As I just ran this playbook and I have a working gitea, but when I make a dump and restore it fails.

**Comment by msgpeek** [comment]
``I am wondering if instead of using sqlite3 it made another type of database``
What is **it**? Ansible, this ansible role, Gitea?

I still don't get it. What drives you to that conclusion? I heavily assume you checked your gitea.ini on the server before opening the issue, right? On the system you backed up, and on the system you restored on.  If both configs are alright, this repo is the wrong place for the issue. I doubt that, too, however. I migrated my gitea v11.5 from FreeBSD to Debian recently. Using the dump command and in both cases SQLite. It worked as expected.

``I've mostly used default settings on my ubuntu 18.04 instance.``
I hope **mostly** is a definitive yes on using SQLite.

No offense, but you don't seem to have made a lot of debugging. If you can't give me some definitive info, I don't see a reason to go on.

**Comment by thepenguinthatwants** [comment]
I d

**Comment by msgpeek** [comment]
What you describe in the link seems like a legit bug. But this has simply nothing to do with this role, imho.
Cheers.
